package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Neuxbane/NeuXbaneProtocol/nxp/abi"
)

// sortedKeys returns the keys of m in deterministic (lexical) order so that
// generated code is stable across builds.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// RouteCodegenItem links a file route with its reflected handler info.
type RouteCodegenItem struct {
	Route       abi.Route
	FileRoute   FileRoute
	HandlerInfo *HandlerInfo
	ImportPath  string
	ImportAlias string
}

// EmitGeneratedRoutes generates the Go source code for internal/generated/routes_gen.go with package generated.
func EmitGeneratedRoutes(modulePath, buildID string, items []RouteCodegenItem, guards []GuardFile) ([]byte, error) {
	return EmitGeneratedRoutesWithPackage("generated", modulePath, buildID, items, guards)
}

// EmitGeneratedRoutesWithPackage generates the Go source code with the specified package name (e.g. main or generated).
func EmitGeneratedRoutesWithPackage(pkgName, modulePath, buildID string, items []RouteCodegenItem, guards []GuardFile) ([]byte, error) {
	if pkgName == "" {
		pkgName = "generated"
	}

	var buf bytes.Buffer

	buf.WriteString("// Code generated by nxp-codegen. DO NOT EDIT.\n")
	buf.WriteString("//\n")
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("//  HARD RULE: THIS FILE IS GENERATED. DO NOT EDIT IT BY HAND.\n")
	buf.WriteString("//  Any manual change will be silently overwritten on the next build.\n")
	buf.WriteString("//  To change routing, guards, or contracts, edit the define/ tree instead.\n")
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("// Build ID: " + buildID + "\n\n")
	buf.WriteString("package " + pkgName + "\n\n")

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n\n")

	if pkgName == "main" {
		buf.WriteString("\t\"abi\"\n")
		buf.WriteString("\t\"abi/errors\"\n")
		buf.WriteString("\t\"abi/rest\"\n")
		buf.WriteString("\t\"abi/files\"\n")
		buf.WriteString("\t\"abi/ws\"\n")
		buf.WriteString("\t\"abi/rtc\"\n")
		buf.WriteString("\t\"abi/mqtt\"\n")
		buf.WriteString("\t\"abi/worker\"\n\n")
	} else {
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/abi\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/errors\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/rest\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/files\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/ws\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/rtc\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/mqtt\"\n")
		buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/internal/worker\"\n\n")
	}

	// Import each handler package
	aliasMap := make(map[string]string)
	for i, item := range items {
		pkgDir := item.FileRoute.PackagePath
		rel, _ := filepath.Rel(".", pkgDir)
		rel = filepath.ToSlash(rel)
		importPath := modulePath + "/" + rel
		alias := fmt.Sprintf("pkg_%d", i)
		aliasMap[item.FileRoute.FilePath] = alias
		buf.WriteString(fmt.Sprintf("\t%s %q\n", alias, importPath))
	}

	// Import each guard package
	guardAliasMap := make(map[string]string)
	for i, g := range guards {
		rel, _ := filepath.Rel(".", g.PackagePath)
		rel = filepath.ToSlash(rel)
		importPath := modulePath + "/" + rel
		alias := fmt.Sprintf("guard_%d", i)
		guardAliasMap[g.ID] = alias
		buf.WriteString(fmt.Sprintf("\t%s %q\n", alias, importPath))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("// Silence unused domain import warnings.\n")
	buf.WriteString("var (\n")
	buf.WriteString("\t_ = context.Background\n")
	buf.WriteString("\t_ = json.Marshal\n")
	buf.WriteString("\t_ = fmt.Sprintf\n")
	buf.WriteString("\t_ = abi.ABIVersion\n")
	buf.WriteString("\t_ = errors.New\n")
	buf.WriteString("\t_ = rest.NewCtx\n")
	buf.WriteString("\t_ = files.NewDownloadCtx\n")
	buf.WriteString("\t_ = ws.NewCtx\n")
	buf.WriteString("\t_ = rtc.NewSessionCtx\n")
	buf.WriteString("\t_ = mqtt.NewCtx[any, any]\n")
	buf.WriteString("\t_ = worker.Runtime{}\n")
	buf.WriteString(")\n\n")

	buf.WriteString(fmt.Sprintf("const BuildID = %q\n\n", buildID))

	// GeneratedRoutes slice
	buf.WriteString("// GeneratedRoutes contains all compiled routes in the project.\n")
	buf.WriteString("var GeneratedRoutes = []abi.Route{\n")
	for _, item := range items {
		buf.WriteString("\t{\n")
		buf.WriteString(fmt.Sprintf("\t\tID: %q,\n", item.Route.ID))
		buf.WriteString(fmt.Sprintf("\t\tTransport: abi.Transport(%q),\n", item.Route.Transport))
		buf.WriteString(fmt.Sprintf("\t\tMethod: %q,\n", item.Route.Method))
		buf.WriteString(fmt.Sprintf("\t\tPath: %q,\n", item.Route.Path))
		if item.Route.Description != "" {
			buf.WriteString(fmt.Sprintf("\t\tDescription: %q,\n", item.Route.Description))
		}
		if item.Route.Auth != "" {
			buf.WriteString(fmt.Sprintf("\t\tAuth: %q,\n", item.Route.Auth))
		}
		if len(item.Route.Scopes) > 0 {
			buf.WriteString(fmt.Sprintf("\t\tScopes: %#v,\n", item.Route.Scopes))
		}
		if len(item.Route.Guards) > 0 {
			buf.WriteString(fmt.Sprintf("\t\tGuards: %#v,\n", item.Route.Guards))
		}
		if item.Route.RateLimit != nil {
			buf.WriteString(fmt.Sprintf("\t\tRateLimit: &abi.RateLimitConfig{RPS: %d, Burst: %d},\n",
				item.Route.RateLimit.RPS, item.Route.RateLimit.Burst))
		}
		if len(item.Route.Metadata) > 0 {
			buf.WriteString("\t\tMetadata: map[string]string{\n")
			for _, k := range sortedKeys(item.Route.Metadata) {
				buf.WriteString(fmt.Sprintf("\t\t\t%q: %q,\n", k, item.Route.Metadata[k]))
			}
			buf.WriteString("\t\t},\n")
		}
		// Shape representation
		buf.WriteString(emitShapeCode(item.Route.Shape))
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n\n")

	// GeneratedContract
	buf.WriteString("// GeneratedContract defines the system-wide contract for this build.\n")
	buf.WriteString("var GeneratedContract = abi.Contract{\n")
	buf.WriteString("\tABIVersion: abi.ABIVersion,\n")
	buf.WriteString("\tBuildID: BuildID,\n")
	buf.WriteString("\tRoutes: GeneratedRoutes,\n")
	buf.WriteString("}\n\n")

	// GeneratedGuards maps every folder-guard ID to its executable adapter.
	// Guards are declared by index.go files and run before every descendant
	// route handler, outermost folder first.
	buf.WriteString("// GeneratedGuards maps every folder-guard ID to an executable adapter.\n")
	buf.WriteString("var GeneratedGuards = map[string]func(*abi.Request) error{\n")
	for _, g := range guards {
		alias := guardAliasMap[g.ID]
		buf.WriteString(fmt.Sprintf("\t%q: func(req *abi.Request) error {\n", g.ID))
		buf.WriteString("\t\tctx := rest.NewCtx(context.Background(), req)\n")
		buf.WriteString(fmt.Sprintf("\t\treturn %s.Guard(ctx)\n", alias))
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n\n")

	// GeneratedRegistry map
	buf.WriteString("// GeneratedRegistry maps every HandlerID to an executable worker adapter.\n")
	buf.WriteString("var GeneratedRegistry = map[abi.HandlerID]worker.HandlerFunc{\n")
	for _, item := range items {
		alias := aliasMap[item.FileRoute.FilePath]
		fnName := "Handler"
		domain := "rest"
		typeName := "Ctx"
		var typeArgs []string
		if item.HandlerInfo != nil {
			if item.HandlerInfo.FunctionName != "" {
				fnName = item.HandlerInfo.FunctionName
			}
			if item.HandlerInfo.Domain != "" {
				domain = item.HandlerInfo.Domain
			}
			if item.HandlerInfo.TypeName != "" {
				typeName = item.HandlerInfo.TypeName
			}
			typeArgs = item.HandlerInfo.TypeArgs
		}

		buf.WriteString(fmt.Sprintf("\t%q: func(req *abi.Request) (*abi.Response, error) {\n", item.Route.ID))
		// Run inherited folder guards before the handler, outermost first.
		for _, gid := range item.Route.Guards {
			buf.WriteString(fmt.Sprintf("\t\tif g, ok := GeneratedGuards[%q]; ok {\n", gid))
			buf.WriteString("\t\t\tif err := g(req); err != nil {\n")
			buf.WriteString("\t\t\t\treturn abi.NewErrorResponse(err), nil\n")
			buf.WriteString("\t\t\t}\n")
			buf.WriteString("\t\t}\n")
		}
		switch {
		case domain == "files" && typeName == "UploadCtx":
			buf.WriteString("\t\tctx, err := files.NewUploadCtx(nil, req.Params, nil)\n")
			buf.WriteString("\t\tif err != nil {\n")
			buf.WriteString("\t\t\treturn abi.NewErrorResponse(err), nil\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "files" && typeName == "DownloadCtx":
			buf.WriteString("\t\tctx := files.NewDownloadCtx(req.Param(\"id\"), req.Params)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "ws":
			buf.WriteString("\t\tctx := ws.NewCtx(context.Background(), req, nil, nil)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "rtc":
			buf.WriteString("\t\tctx := rtc.NewSessionCtx(context.Background(), req, nil)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "mqtt":
			if len(typeArgs) >= 2 {
				buf.WriteString(fmt.Sprintf("\t\tctx := mqtt.NewCtx[%s.%s, %s.%s](context.Background(), req, nil)\n", alias, typeArgs[0], alias, typeArgs[1]))
			} else {
				buf.WriteString("\t\tctx := mqtt.NewCtx[any, any](context.Background(), req, nil)\n")
			}
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		default:
			buf.WriteString("\t\tctx := rest.NewCtx(context.Background(), req)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		}
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString("\t\t\treturn abi.NewErrorResponse(err), nil\n")
		buf.WriteString("\t\t}\n")
		if domain == "rest" || domain == "" {
			buf.WriteString("\t\treturn abi.NewAutoResponse(ctx.Response(), 200, res)\n")
		} else {
			buf.WriteString("\t\treturn abi.NewAutoResponse(nil, 200, res)\n")
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted if format error so caller can debug
		return buf.Bytes(), fmt.Errorf("format emitted code: %w\nRaw:\n%s", err, buf.String())
	}

	return formatted, nil
}

func emitShapeCode(shape abi.Shape) string {
	if shape == nil {
		return "\t\tShape: abi.RequestResponseShape{},\n"
	}
	switch s := shape.(type) {
	case abi.RequestResponseShape:
		reqBytes, _ := json.Marshal(s.Request)
		resBytes, _ := json.Marshal(s.Responses[200])
		return fmt.Sprintf("\t\tShape: abi.RequestResponseShape{\n\t\t\tRequest: abi.MustCompile([]byte(%q)),\n\t\t\tResponses: map[int]*abi.Schema{200: abi.MustCompile([]byte(%q))},\n\t\t},\n", string(reqBytes), string(resBytes))
	case abi.FramesShape:
		return "\t\tShape: abi.FramesShape{\n\t\t\tIn: &abi.Schema{Type: \"string\"},\n\t\t\tOut: &abi.Schema{Type: \"string\"},\n\t\t},\n"
	case abi.DatagramShape:
		return fmt.Sprintf("\t\tShape: abi.DatagramShape{\n\t\t\tMaxSize: %d,\n\t\t\tResponse: abi.DatagramResponse(%q),\n\t\t},\n", s.MaxSize, s.Response)
	case abi.PubSubShape:
		topicsMap := "map[string]string{"
		for k, v := range s.Topics {
			topicsMap += fmt.Sprintf("%q: %q, ", k, v)
		}
		topicsMap += "}"
		return fmt.Sprintf("\t\tShape: abi.PubSubShape{\n\t\t\tTopics: %s,\n\t\t\tQoS: %d,\n\t\t\tRetain: %t,\n\t\t},\n", topicsMap, s.QoS, s.Retain)
	case abi.StreamShape:
		return fmt.Sprintf("\t\tShape: abi.StreamShape{\n\t\t\tPartitions: %d,\n\t\t\tConsumerGroup: %q,\n\t\t},\n", s.Partitions, s.ConsumerGroup)
	default:
		return "\t\tShape: abi.RequestResponseShape{},\n"
	}
}

// GenerateProject runs the complete codegen pipeline across defineDir.
func GenerateProject(defineDir, modulePath, outputGenFile, buildIDFile string) (string, error) {
	// Stage the authoring tree so "@param" segments compile (see StageDefineTree).
	stageDir := filepath.Join(filepath.Dir(outputGenFile), "define")
	if _, err := StageDefineTree(defineDir, stageDir); err != nil {
		return "", fmt.Errorf("stage define tree: %w", err)
	}

	fileRoutes, err := WalkDefineTree(stageDir)
	if err != nil {
		return "", fmt.Errorf("walk define tree: %w", err)
	}

	guards, err := WalkGuards(stageDir)
	if err != nil {
		return "", fmt.Errorf("walk guards: %w", err)
	}

	buildID, err := ComputeBuildID(defineDir)
	if err != nil {
		return "", fmt.Errorf("compute build id: %w", err)
	}

	var items []RouteCodegenItem
	for _, fr := range fileRoutes {
		info, _ := InspectHandlerSource(fr.FilePath, fr.Content)

		handlerID := strings.TrimPrefix(fr.Path, "/")
		handlerID = strings.ReplaceAll(handlerID, "/", ".")
		if handlerID == "" {
			handlerID = "index"
		}
		handlerID = strings.ToLower(fr.Method) + "." + handlerID

		shape := BuildShape(fr.Transport, fr.Directives, info)

		route := abi.Route{
			ID:          abi.HandlerID(handlerID),
			Transport:   fr.Transport,
			Method:      fr.Method,
			Path:        fr.Path,
			Description: fr.Directives.Description,
			Auth:        fr.Directives.Auth,
			Scopes:      fr.Directives.Scopes,
			Guards:      fr.Guards,
			RateLimit:   fr.Directives.RateLimit,
			Shape:       shape,
			Metadata:    buildRouteMetadata(fr.Directives),
		}

		items = append(items, RouteCodegenItem{
			Route:       route,
			FileRoute:   fr,
			HandlerInfo: info,
		})
	}

	code, err := EmitGeneratedRoutes(modulePath, buildID, items, guards)
	if err != nil {
		return "", fmt.Errorf("emit routes: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outputGenFile), 0755); err != nil {
		return "", fmt.Errorf("mkdir generated: %w", err)
	}

	if err := os.WriteFile(outputGenFile, code, 0644); err != nil {
		return "", fmt.Errorf("write generated routes: %w", err)
	}

	if buildIDFile != "" {
		_ = WriteBuildIDFile(buildIDFile, buildID)
	}

	return buildID, nil
}

// EmitWorkerMain returns the source code for the generated worker process main.go.
func EmitWorkerMain() []byte {
	return []byte(`// Code generated by nxp-codegen. DO NOT EDIT.
//
// ============================================================================
//  HARD RULE: THIS FILE IS GENERATED. DO NOT EDIT IT BY HAND.
//  Any manual change will be silently overwritten on the next build.
// ============================================================================
package main

import (
	"context"
	"fmt"
	"os"

	"abi/worker"
)

func main() {
	workerName := os.Getenv("WORKER_NAME")
	if workerName == "" {
		workerName = "nxp-worker"
	}
	buildID := os.Getenv("BUILD_ID")
	if buildID == "" {
		buildID = BuildID
	}
	sockPath := os.Getenv("WORKER_SOCK")

	w := worker.NewRuntime(workerName, buildID, sockPath)

	for _, route := range GeneratedRoutes {
		if handler, ok := GeneratedRegistry[route.ID]; ok {
			w.RegisterHandler(route, handler)
		}
	}

	if err := w.Start(context.Background()); err != nil {
		fmt.Fprintf(os.Stderr, "worker error: %v\n", err)
		os.Exit(1)
	}
}
`)
}

// GenerateWorkerProject generates a self-contained worker package under workerDir.
func GenerateWorkerProject(defineDir, modulePath, workerDir, buildIDFile string) (string, error) {
	// Stage the authoring tree into a Go-compilable copy. Dynamic route
	// segments are authored as "@param" but Go import paths reject "@", so the
	// staged tree renames them to "_param" and normalizes package clauses.
	stageDir := filepath.Join(workerDir, "define")
	if _, err := StageDefineTree(defineDir, stageDir); err != nil {
		return "", fmt.Errorf("stage define tree: %w", err)
	}

	fileRoutes, err := WalkDefineTree(stageDir)
	if err != nil {
		return "", fmt.Errorf("walk define tree: %w", err)
	}

	guards, err := WalkGuards(stageDir)
	if err != nil {
		return "", fmt.Errorf("walk guards: %w", err)
	}

	buildID, err := ComputeBuildID(defineDir)
	if err != nil {
		return "", fmt.Errorf("compute build id: %w", err)
	}

	var items []RouteCodegenItem
	for _, fr := range fileRoutes {
		info, _ := InspectHandlerSource(fr.FilePath, fr.Content)

		handlerID := strings.TrimPrefix(fr.Path, "/")
		handlerID = strings.ReplaceAll(handlerID, "/", ".")
		if handlerID == "" {
			handlerID = "index"
		}
		handlerID = strings.ToLower(fr.Method) + "." + handlerID

		shape := BuildShape(fr.Transport, fr.Directives, info)

		route := abi.Route{
			ID:          abi.HandlerID(handlerID),
			Transport:   fr.Transport,
			Method:      fr.Method,
			Path:        fr.Path,
			Description: fr.Directives.Description,
			Auth:        fr.Directives.Auth,
			Scopes:      fr.Directives.Scopes,
			Guards:      fr.Guards,
			RateLimit:   fr.Directives.RateLimit,
			Shape:       shape,
			Metadata:    buildRouteMetadata(fr.Directives),
		}

		items = append(items, RouteCodegenItem{
			Route:       route,
			FileRoute:   fr,
			HandlerInfo: info,
		})
	}

	// 1. Emit package main routes for worker
	codeMain, err := EmitGeneratedRoutesWithPackage("main", modulePath, buildID, items, guards)
	if err != nil {
		return "", fmt.Errorf("emit worker routes: %w", err)
	}

	if err := os.MkdirAll(workerDir, 0755); err != nil {
		return "", fmt.Errorf("mkdir worker dir: %w", err)
	}

	routesFile := filepath.Join(workerDir, "routes_gen.go")
	if err := os.WriteFile(routesFile, codeMain, 0644); err != nil {
		return "", fmt.Errorf("write worker routes: %w", err)
	}

	mainFile := filepath.Join(workerDir, "main.go")
	if err := os.WriteFile(mainFile, EmitWorkerMain(), 0644); err != nil {
		return "", fmt.Errorf("write worker main: %w", err)
	}

	// 2. Also emit package generated if internal/generated directory exists (for compatibility with cmd/nxp-worker & tests)
	if info, err := os.Stat("internal/generated"); err == nil && info.IsDir() {
		codeGen, err := EmitGeneratedRoutesWithPackage("generated", modulePath, buildID, items, guards)
		if err == nil {
			_ = os.WriteFile("internal/generated/routes_gen.go", codeGen, 0644)
		}
	}

	if buildIDFile != "" {
		_ = WriteBuildIDFile(buildIDFile, buildID)
	}

	return buildID, nil
}
