package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/Neuxbane/NeuXbaneProtocol/nxp/abi"
)

// RouteCodegenItem links a file route with its reflected handler info.
type RouteCodegenItem struct {
	Route       abi.Route
	FileRoute   FileRoute
	HandlerInfo *HandlerInfo
	ImportPath  string
	ImportAlias string
}

// EmitGeneratedRoutes generates the Go source code for internal/generated/routes_gen.go.
func EmitGeneratedRoutes(modulePath, buildID string, items []RouteCodegenItem) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by nxp-codegen. DO NOT EDIT.\n")
	buf.WriteString("// Build ID: " + buildID + "\n\n")
	buf.WriteString("package generated\n\n")

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/abi\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/errors\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/rest\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/files\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/ws\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/rtc\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/nxp/mqtt\"\n")
	buf.WriteString("\t\"github.com/Neuxbane/NeuXbaneProtocol/internal/worker\"\n\n")

	// Import each handler package
	aliasMap := make(map[string]string)
	for i, item := range items {
		pkgDir := item.FileRoute.PackagePath
		rel, _ := filepath.Rel(".", pkgDir)
		rel = filepath.ToSlash(rel)
		importPath := modulePath + "/" + rel
		alias := fmt.Sprintf("pkg_%d", i)
		aliasMap[item.FileRoute.FilePath] = alias
		buf.WriteString(fmt.Sprintf("\t%s %q\n", alias, importPath))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("// Silence unused domain import warnings.\n")
	buf.WriteString("var (\n")
	buf.WriteString("\t_ = context.Background\n")
	buf.WriteString("\t_ = json.Marshal\n")
	buf.WriteString("\t_ = fmt.Sprintf\n")
	buf.WriteString("\t_ = abi.ABIVersion\n")
	buf.WriteString("\t_ = errors.New\n")
	buf.WriteString("\t_ = rest.NewCtx\n")
	buf.WriteString("\t_ = files.NewDownloadCtx\n")
	buf.WriteString("\t_ = ws.NewCtx\n")
	buf.WriteString("\t_ = rtc.NewSessionCtx\n")
	buf.WriteString("\t_ = mqtt.NewCtx[any, any]\n")
	buf.WriteString("\t_ = worker.Runtime{}\n")
	buf.WriteString(")\n\n")

	buf.WriteString(fmt.Sprintf("const BuildID = %q\n\n", buildID))

	// GeneratedRoutes slice
	buf.WriteString("// GeneratedRoutes contains all compiled routes in the project.\n")
	buf.WriteString("var GeneratedRoutes = []abi.Route{\n")
	for _, item := range items {
		buf.WriteString("\t{\n")
		buf.WriteString(fmt.Sprintf("\t\tID: %q,\n", item.Route.ID))
		buf.WriteString(fmt.Sprintf("\t\tTransport: abi.Transport(%q),\n", item.Route.Transport))
		buf.WriteString(fmt.Sprintf("\t\tMethod: %q,\n", item.Route.Method))
		buf.WriteString(fmt.Sprintf("\t\tPath: %q,\n", item.Route.Path))
		if item.Route.Auth != "" {
			buf.WriteString(fmt.Sprintf("\t\tAuth: %q,\n", item.Route.Auth))
		}
		if len(item.Route.Scopes) > 0 {
			buf.WriteString(fmt.Sprintf("\t\tScopes: %#v,\n", item.Route.Scopes))
		}
		if item.Route.RateLimit != nil {
			buf.WriteString(fmt.Sprintf("\t\tRateLimit: &abi.RateLimitConfig{RPS: %d, Burst: %d},\n",
				item.Route.RateLimit.RPS, item.Route.RateLimit.Burst))
		}
		// Shape representation
		buf.WriteString(emitShapeCode(item.Route.Shape))
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n\n")

	// GeneratedContract
	buf.WriteString("// GeneratedContract defines the system-wide contract for this build.\n")
	buf.WriteString("var GeneratedContract = abi.Contract{\n")
	buf.WriteString("\tABIVersion: abi.ABIVersion,\n")
	buf.WriteString("\tBuildID: BuildID,\n")
	buf.WriteString("\tRoutes: GeneratedRoutes,\n")
	buf.WriteString("}\n\n")

	// GeneratedRegistry map
	buf.WriteString("// GeneratedRegistry maps every HandlerID to an executable worker adapter.\n")
	buf.WriteString("var GeneratedRegistry = map[abi.HandlerID]worker.HandlerFunc{\n")
	for _, item := range items {
		alias := aliasMap[item.FileRoute.FilePath]
		fnName := "Handler"
		domain := "rest"
		typeName := "Ctx"
		var typeArgs []string
		if item.HandlerInfo != nil {
			if item.HandlerInfo.FunctionName != "" {
				fnName = item.HandlerInfo.FunctionName
			}
			if item.HandlerInfo.Domain != "" {
				domain = item.HandlerInfo.Domain
			}
			if item.HandlerInfo.TypeName != "" {
				typeName = item.HandlerInfo.TypeName
			}
			typeArgs = item.HandlerInfo.TypeArgs
		}

		buf.WriteString(fmt.Sprintf("\t%q: func(req *abi.Request) (*abi.Response, error) {\n", item.Route.ID))
		switch {
		case domain == "files" && typeName == "UploadCtx":
			buf.WriteString("\t\tctx, err := files.NewUploadCtx(nil, req.Params, nil)\n")
			buf.WriteString("\t\tif err != nil {\n")
			buf.WriteString("\t\t\treturn abi.NewErrorResponse(err), nil\n")
			buf.WriteString("\t\t}\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "files" && typeName == "DownloadCtx":
			buf.WriteString("\t\tctx := files.NewDownloadCtx(req.Param(\"id\"), req.Params)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "ws":
			buf.WriteString("\t\tctx := ws.NewCtx(context.Background(), req, nil, nil)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "rtc":
			buf.WriteString("\t\tctx := rtc.NewSessionCtx(context.Background(), req, nil)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		case domain == "mqtt":
			if len(typeArgs) >= 2 {
				buf.WriteString(fmt.Sprintf("\t\tctx := mqtt.NewCtx[%s.%s, %s.%s](context.Background(), req, nil)\n", alias, typeArgs[0], alias, typeArgs[1]))
			} else {
				buf.WriteString("\t\tctx := mqtt.NewCtx[any, any](context.Background(), req, nil)\n")
			}
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		default:
			buf.WriteString("\t\tctx := rest.NewCtx(context.Background(), req)\n")
			buf.WriteString(fmt.Sprintf("\t\tres, err := %s.%s(ctx)\n", alias, fnName))
		}
		buf.WriteString("\t\tif err != nil {\n")
		buf.WriteString("\t\t\treturn abi.NewErrorResponse(err), nil\n")
		buf.WriteString("\t\t}\n")
		buf.WriteString("\t\treturn abi.NewJSONResponse(200, res)\n")
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted if format error so caller can debug
		return buf.Bytes(), fmt.Errorf("format emitted code: %w\nRaw:\n%s", err, buf.String())
	}

	return formatted, nil
}

func emitShapeCode(shape abi.Shape) string {
	if shape == nil {
		return "\t\tShape: abi.RequestResponseShape{},\n"
	}
	switch s := shape.(type) {
	case abi.RequestResponseShape:
		return "\t\tShape: abi.RequestResponseShape{\n\t\t\tRequest: &abi.Schema{Type: \"object\"},\n\t\t\tResponses: map[int]*abi.Schema{200: {Type: \"object\"}},\n\t\t},\n"
	case abi.FramesShape:
		return "\t\tShape: abi.FramesShape{\n\t\t\tIn: &abi.Schema{Type: \"string\"},\n\t\t\tOut: &abi.Schema{Type: \"string\"},\n\t\t},\n"
	case abi.DatagramShape:
		return fmt.Sprintf("\t\tShape: abi.DatagramShape{\n\t\t\tMaxSize: %d,\n\t\t\tResponse: abi.DatagramResponse(%q),\n\t\t},\n", s.MaxSize, s.Response)
	case abi.PubSubShape:
		topicsMap := "map[string]string{"
		for k, v := range s.Topics {
			topicsMap += fmt.Sprintf("%q: %q, ", k, v)
		}
		topicsMap += "}"
		return fmt.Sprintf("\t\tShape: abi.PubSubShape{\n\t\t\tTopics: %s,\n\t\t\tQoS: %d,\n\t\t\tRetain: %t,\n\t\t},\n", topicsMap, s.QoS, s.Retain)
	case abi.StreamShape:
		return fmt.Sprintf("\t\tShape: abi.StreamShape{\n\t\t\tPartitions: %d,\n\t\t\tConsumerGroup: %q,\n\t\t},\n", s.Partitions, s.ConsumerGroup)
	default:
		return "\t\tShape: abi.RequestResponseShape{},\n"
	}
}

// GenerateProject runs the complete codegen pipeline across defineDir.
func GenerateProject(defineDir, modulePath, outputGenFile, buildIDFile string) (string, error) {
	fileRoutes, err := WalkDefineTree(defineDir)
	if err != nil {
		return "", fmt.Errorf("walk define tree: %w", err)
	}

	buildID, err := ComputeBuildID(defineDir)
	if err != nil {
		return "", fmt.Errorf("compute build id: %w", err)
	}

	var items []RouteCodegenItem
	for _, fr := range fileRoutes {
		info, _ := InspectHandlerSource(fr.FilePath, fr.Content)

		handlerID := strings.TrimPrefix(fr.Path, "/")
		handlerID = strings.ReplaceAll(handlerID, "/", ".")
		if handlerID == "" {
			handlerID = "index"
		}
		handlerID = strings.ToLower(fr.Method) + "." + handlerID

		shape := BuildShape(fr.Transport, fr.Directives, info)

		route := abi.Route{
			ID:        abi.HandlerID(handlerID),
			Transport: fr.Transport,
			Method:    fr.Method,
			Path:      fr.Path,
			Auth:      fr.Directives.Auth,
			Scopes:    fr.Directives.Scopes,
			RateLimit: fr.Directives.RateLimit,
			Shape:     shape,
		}

		items = append(items, RouteCodegenItem{
			Route:       route,
			FileRoute:   fr,
			HandlerInfo: info,
		})
	}

	code, err := EmitGeneratedRoutes(modulePath, buildID, items)
	if err != nil {
		return "", fmt.Errorf("emit routes: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outputGenFile), 0755); err != nil {
		return "", fmt.Errorf("mkdir generated: %w", err)
	}

	if err := os.WriteFile(outputGenFile, code, 0644); err != nil {
		return "", fmt.Errorf("write generated routes: %w", err)
	}

	if buildIDFile != "" {
		_ = WriteBuildIDFile(buildIDFile, buildID)
	}

	return buildID, nil
}
